-- KnowRa — KnowRa Pro: assinatura via Mercado Pago, gating de IA e Concursos
-- Item #3 da estratégia de sustentabilidade financeira (ver ROADMAP.md e
-- DECISIONS.md), depois de cache (#1) e limite diário de IA (#2). Escopo
-- combinado com o Ronaldo: mais interações de IA por dia, acesso ampliado
-- a Concursos, flag "sem anúncios" reservada pro item #6 (ainda não existe
-- publicidade, então essa flag não tem efeito prático agora).

-- 1) Ordem estável de geração das questões — necessária pro teto gratuito
-- de Concursos ser determinístico. criado_em pode empatar quando um lote
-- inteiro é inserido na mesma transação (gerar_questoes.ts insere várias
-- linhas de uma vez, e "now()" é estável dentro de uma transação).
alter table public.questoes add column ordem bigint generated by default as identity;

-- 2) Plano do usuário
alter table public.profiles add column plano text not null default 'free' check (plano in ('free', 'pro'));

-- 3) Assinaturas (Mercado Pago Preapproval / assinatura recorrente)
create table public.assinaturas (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.profiles (id) on delete cascade,
  mp_preapproval_id text unique,
  status text not null default 'pending' check (status in ('pending', 'authorized', 'paused', 'cancelled')),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

alter table public.assinaturas enable row level security;
revoke all on table public.assinaturas from anon, authenticated;
grant select on table public.assinaturas to authenticated;

create policy "usuario le a propria assinatura"
  on public.assinaturas for select
  using (auth.uid() = usuario_id or public.is_admin(auth.uid()));

-- Só o webhook do Mercado Pago (backend, via DATABASE_URL — nunca
-- service_role, mesmo padrão já usado em gerar_questoes.ts) grava
-- status/plano. Nenhum grant de insert/update pra anon/authenticated —
-- criar_assinatura_pendente()/registrar_mp_preapproval() abaixo são as
-- únicas portas de escrita do lado do usuário, e ambas restritas a
-- auth.uid() dono da linha.

create or replace function public.criar_assinatura_pendente()
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  insert into public.assinaturas (usuario_id, status)
  values (auth.uid(), 'pending')
  returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.criar_assinatura_pendente() from public, anon;
grant execute on function public.criar_assinatura_pendente() to authenticated;

create or replace function public.registrar_mp_preapproval(p_assinatura_id uuid, p_mp_preapproval_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.assinaturas
    set mp_preapproval_id = p_mp_preapproval_id, atualizado_em = now()
    where id = p_assinatura_id and usuario_id = auth.uid();

  if not found then
    raise exception 'Assinatura não encontrada.';
  end if;
end;
$$;

revoke all on function public.registrar_mp_preapproval(uuid, text) from public, anon;
grant execute on function public.registrar_mp_preapproval(uuid, text) to authenticated;

-- Frontend usa pra mostrar plano/status ("Você é Pro" / "Assinar Pro").
create or replace function public.minha_assinatura()
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_plano text;
  v_assinatura public.assinaturas;
begin
  select plano into v_plano from public.profiles where profiles.id = auth.uid();

  select * into v_assinatura from public.assinaturas
    where usuario_id = auth.uid()
    order by criado_em desc
    limit 1;

  return jsonb_build_object(
    'plano', coalesce(v_plano, 'free'),
    'status_assinatura', v_assinatura.status,
    'atualizado_em', v_assinatura.atualizado_em
  );
end;
$$;

revoke all on function public.minha_assinatura() from public, anon;
grant execute on function public.minha_assinatura() to authenticated;

-- 4) Gating de IA: plano pro sobe o teto diário (número provisório, mesmo
-- espírito do 5/dia gratuito — ajustável quando houver dado real de custo).
create or replace function public.verificar_limite_ia()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limite_free constant int := 5;
  v_limite_pro constant int := 30;
  v_limite int;
  v_usadas int;
  v_plano text;
begin
  if public.is_admin(auth.uid()) then
    return jsonb_build_object('permitido', true, 'usadas_hoje', 0, 'limite', v_limite_free, 'ilimitado', true);
  end if;

  select plano into v_plano from public.profiles where profiles.id = auth.uid();
  v_limite := case when v_plano = 'pro' then v_limite_pro else v_limite_free end;

  select chamadas into v_usadas
    from public.ia_uso_diario
    where usuario_id = auth.uid() and dia = current_date;
  v_usadas := coalesce(v_usadas, 0);

  if v_usadas >= v_limite then
    return jsonb_build_object('permitido', false, 'usadas_hoje', v_usadas, 'limite', v_limite, 'ilimitado', false);
  end if;

  insert into public.ia_uso_diario (usuario_id, dia, chamadas)
  values (auth.uid(), current_date, 1)
  on conflict (usuario_id, dia) do update set chamadas = public.ia_uso_diario.chamadas + 1;

  return jsonb_build_object('permitido', true, 'usadas_hoje', v_usadas + 1, 'limite', v_limite, 'ilimitado', false);
end;
$$;

create or replace function public.meu_uso_ia()
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_limite_free constant int := 5;
  v_limite_pro constant int := 30;
  v_limite int;
  v_usadas int;
  v_plano text;
begin
  if public.is_admin(auth.uid()) then
    return jsonb_build_object('usadas_hoje', 0, 'limite', v_limite_free, 'ilimitado', true);
  end if;

  select plano into v_plano from public.profiles where profiles.id = auth.uid();
  v_limite := case when v_plano = 'pro' then v_limite_pro else v_limite_free end;

  select chamadas into v_usadas
    from public.ia_uso_diario
    where usuario_id = auth.uid() and dia = current_date;

  return jsonb_build_object('usadas_hoje', coalesce(v_usadas, 0), 'limite', v_limite, 'ilimitado', false);
end;
$$;

-- 5) Gating de Concursos: free só enxerga as 10 primeiras questões (por
-- ordem de geração) de cada concurso. Prática por disciplina (p_area_id)
-- continua sem teto pra todo mundo — é a porta de entrada gratuita.
create or replace function public.listar_questoes(
  p_concurso_id uuid default null,
  p_area_id uuid default null,
  p_limite int default 20
)
returns table (
  id uuid,
  enunciado text,
  alternativas jsonb,
  dificuldade text,
  area_id uuid
)
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_limite_free_concurso constant int := 10;
  v_plano text;
  v_limite_efetivo int;
begin
  if p_concurso_id is null and p_area_id is null then
    raise exception 'Informe p_concurso_id ou p_area_id.';
  end if;

  v_limite_efetivo := greatest(1, least(coalesce(p_limite, 20), 100));

  if p_concurso_id is not null then
    select plano into v_plano from public.profiles where profiles.id = auth.uid();
    if coalesce(v_plano, 'free') <> 'pro' then
      v_limite_efetivo := least(v_limite_efetivo, v_limite_free_concurso);
    end if;
  end if;

  return query
  select q.id, q.enunciado, q.alternativas, q.dificuldade, q.area_id
  from public.questoes q
  where q.review_status = 'published'
    and (p_concurso_id is null or q.concurso_id = p_concurso_id)
    and (p_area_id is null or q.area_id = p_area_id)
  order by q.ordem
  limit v_limite_efetivo;
end;
$$;

revoke all on function public.listar_questoes(uuid, uuid, int) from public, anon;
grant execute on function public.listar_questoes(uuid, uuid, int) to authenticated;

-- responder_questao precisa do mesmo teto — sem isso, um usuário free
-- poderia contornar o paywall chamando a RPC direto com o id de uma
-- questão que listar_questoes() nunca devolveu pra ele (IDOR de conteúdo).
create or replace function public.responder_questao(p_questao_id uuid, p_alternativa text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limite_free_concurso constant int := 10;
  v_questao public.questoes;
  v_correta boolean;
  v_valida boolean;
  v_progresso public.progresso_concurso;
  v_plano text;
  v_posicao int;
begin
  select * into v_questao from public.questoes
    where id = p_questao_id and review_status = 'published';

  if v_questao is null then
    raise exception 'Questão não encontrada ou não disponível.';
  end if;
  if p_alternativa is null or char_length(trim(p_alternativa)) = 0 then
    raise exception 'Alternativa inválida.';
  end if;

  if v_questao.concurso_id is not null then
    select plano into v_plano from public.profiles where profiles.id = auth.uid();
    if coalesce(v_plano, 'free') <> 'pro' then
      select count(*) into v_posicao
        from public.questoes
        where concurso_id = v_questao.concurso_id
          and review_status = 'published'
          and ordem <= v_questao.ordem;
      if v_posicao > v_limite_free_concurso then
        raise exception 'Esta questão faz parte do conteúdo KnowRa Pro.';
      end if;
    end if;
  end if;

  v_correta := (p_alternativa = v_questao.gabarito);

  select not exists (
    select 1 from public.tentativas_questao
    where questao_id = p_questao_id and usuario_id = auth.uid()
  ) into v_valida;

  insert into public.tentativas_questao
    (questao_id, usuario_id, alternativa_escolhida, correta, valida_para_progresso)
  values (p_questao_id, auth.uid(), p_alternativa, v_correta, v_valida);

  if v_valida and v_questao.concurso_id is not null then
    insert into public.progresso_concurso
      (usuario_id, concurso_id, total_questoes_validas, acertos_validos, dominio_pct, atualizado_em)
    values (
      auth.uid(), v_questao.concurso_id, 1,
      case when v_correta then 1 else 0 end,
      case when v_correta then 100 else 0 end,
      now()
    )
    on conflict (usuario_id, concurso_id) do update
      set total_questoes_validas = public.progresso_concurso.total_questoes_validas + 1,
          acertos_validos = public.progresso_concurso.acertos_validos + case when v_correta then 1 else 0 end,
          dominio_pct = round(
            100.0 * (public.progresso_concurso.acertos_validos + case when v_correta then 1 else 0 end)
            / (public.progresso_concurso.total_questoes_validas + 1), 2),
          atualizado_em = now()
    returning * into v_progresso;
  end if;

  return jsonb_build_object(
    'correta', v_correta,
    'gabarito', v_questao.gabarito,
    'explicacao', v_questao.explicacao,
    'valida_para_progresso', v_valida,
    'dominio_pct_concurso', v_progresso.dominio_pct
  );
end;
$$;

revoke all on function public.responder_questao(uuid, text) from public, anon;
grant execute on function public.responder_questao(uuid, text) to authenticated;

-- 6) catalogo_concursos passa a expor quanto é grátis vs. total — sem isso
-- a tela mostraria "37 questões disponíveis" pra um usuário free que só
-- consegue responder 10, o que seria dado enganoso (proibido pelo
-- CLAUDE.md: nunca apresentar informação de um jeito que engane o usuário).
drop function if exists public.catalogo_concursos(int);

create or replace function public.catalogo_concursos(p_limite int default 50)
returns table (
  id uuid,
  nome text,
  orgao text,
  banca text,
  ano int,
  cargo text,
  total_questoes bigint,
  questoes_gratis bigint
)
language sql
security definer
set search_path = public
stable
as $$
  select c.id, c.nome, c.orgao, c.banca, c.ano, c.cargo,
    count(q.id) as total_questoes,
    least(count(q.id), 10) as questoes_gratis
  from public.concursos c
  join public.questoes q on q.concurso_id = c.id and q.review_status = 'published'
  where c.ativo = true
  group by c.id
  order by c.criado_em desc
  limit greatest(1, least(coalesce(p_limite, 50), 100));
$$;

revoke all on function public.catalogo_concursos(int) from public, anon;
grant execute on function public.catalogo_concursos(int) to authenticated;
